@@ .. @@
   const menuItems = [
     {
       id: 'dashboard',
       label: 'Analytics',
       icon: BarChart3,
-      path: '/admin/dashboard',
+      path: '/dashboard',
       roles: ['super-admin', 'sarthi-admin', 'brahma-admin', 'kavach-admin'],
     },
     {
       id: 'customers',
       label: 'Customers',
       icon: Users,
-      path: '/admin/customers',
+      path: '/customers',
       roles: ['super-admin'],
     },
     {
       id: 'sarthi',
       label: 'Sarthi',
       icon: HelpCircle,
-      path: '/admin/sarthi',
+      path: '/sarthi',
       roles: ['super-admin', 'sarthi-admin'],
     },
     {
       id: 'brahma',
       label: 'Brahma',
       icon: Star,
-      path: '/admin/brahma',
+      path: '/brahma',
       roles: ['super-admin', 'brahma-admin'],
     },
     {
       id: 'kavach',
       label: 'Kavach',
       icon: ShoppingBag,
-      path: '/admin/kavach',
+      path: '/kavach',
       roles: ['super-admin', 'kavach-admin'],
     },
     {
       id: 'payments',
       label: 'Payments',
       icon: CreditCard,
-      path: '/admin/payments',
+      path: '/payments',
       roles: ['super-admin'],
     },
     {
       id: 'experts',
       label: 'Experts',
       icon: UserCheck,
-      path: '/admin/experts',
+      path: '/experts',
       roles: ['super-admin', 'sarthi-admin'],
     },
     {
       id: 'settings',
       label: 'Settings',
       icon: Settings,
-      path: '/admin/settings',
+      path: '/settings',
       roles: ['super-admin', 'sarthi-admin', 'brahma-admin', 'kavach-admin'],
     },
   ];